# .github/workflows/review-override.yml
name: Ahhhhh test

on:
  pull_request_review:

permissions:
  statuses: write      # Needed to read and write commit statuses
  pull-requests: read  # Needed to get PR details

# Only run this job if the review state is 'approved'
jobs:
  huh: 
    runs-on: ubuntu-latest
    steps: 
      - name: Sanity check on this running... 
        run: echo "This is a test run"

