# .github/workflows/ahhh.yml
name: Ahhhhh test

on:
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
permissions:
  pull-requests: read  # Needed to get PR details

# Only run this job if the review state is 'approved'
jobs:
  huh: 
    runs-on: ubuntu-latest
    steps: 
      - name: Sanity check on this running... 
        run: echo "This is a test run"

